language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: eKxchurL+P3tZF7tBB+V5CHGZTLKYEea3W0P4QZ1SuB9/VAQgEIJTvsNYH5k3BqbBhr0hfZ02VVQhkHT8uQrNOuZcBSA0EsX3Th86c3YpjQAojAGORWOYDSLQvrAiNr1swFUFqi9IsKr9rwonUe6SEgz6fhwl9WQhZ+MKxIZDClSVq8F8taXsw5zTi6qNj6ezuIEv9INN27RzwQD3OsBRLiYe3An2iRvUAfU8zBvmIqebV+M5Fz8dpS66gpvj61q67atzy+/uEFfniMx+2YrdpVqo8ZTClVWTlo5IP+z/v4ktqmr13eudMyC1CIRDi9QOKkKq2Ny9LHDcL27u6olarGn5BIMwe0F497T7ZrA5c9Aq+f1QDry0TnZQfs5p5VuLfTRWCo6iVUB1V8GCzBwtD8FnOKa5o0haUoJsIYNG2ID7fYzWXenGTvGeM+CkRlmEL9XF9Pn6+fe+L0K4kp3i4lLiSReOAWJW0FjRDDKnEMTCvOb1pPQnDronayp2GluCiJfTlilc+V+F0f49F/+1yC7kcOuo3/Zk/c5WGGEWyxMyYGViSSd8YCv6yT4pkwlL/QaHHH9h+f3ZU2qaQgrRrmT1qoU9LXEeaDufZOtYeZzhC6gAeodeFg+jAZojMFJweb0sBjCrO/QS0VwAjf8TDECqTYpP/+XDKwu2gBL3SQ=
