language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: brave-new-world-123123123
  api_key:
    secure: 3ejO/0+0dcTge06Zg3ptgh9YasVkIdHe9w55ekfpJLa8Hkw+Yb24Lu6qG+Kr5mvtH62aCgsnDpJCFuUHIWqA/GQmDcbc1vV4knMnpdhU0rAbwDUkpWtSWjaGtMybYZMQy2vvxUPFsz/PiSm4smsgcJ4Bv8CU7gK7or+Mpffnx2mQSWfcvSI3ucec7WRfNn6LZIpqtMB9Qe9WJQWhOJ2YcU0l008q/zWZtSe8HDxmCKBZARskmoHE4BZUfS7pNYopwAs4Ax+GOhIG0ffRYD3BPUJBjeR9BHgGcA/N92PfCtrN/adeJ5/UmUl1cAIqkn0J++Bc4h27OyzVfcuximp76h+wfvXRIjQhVVnTY0BraEkOSuCZ6/mJ7iRuxiGEKtgoB8k7SsSGOidz5Gqz/dPtCPbCn5hvc1zgzqk8tHZyc8dXA0a/157s1dD66fOn3TrcbgDoJosv4ZKE9x4HhE5PSOdnUbMQJHSX7Q8jfsGNroeeT7bPQ3YgHz5ymBpVPeMHVhg6VBvw3EOqrjUIkeBdDCgIRsB/Ni6RdGTbX5tH5kT0nUfQb9klmJZr7ItgVZZjzOzWzapCkcbZc5Xm686ssJaRdiKx3Syr7zXgXM2Vi/4Gmf/0t/dzRSquyIegHXYjCAFK6RZNNy7ITrYFuTCjuLsnF5RG272xOppFcT50Rms=
